export default {
  translation: {
    accueil: "Home",
    films: "Movies",
    series: "Series",
    actualites: "News",
    connexion: "Login",
    inscription: "Sign up",
    bienvenue: "Welcome to Cineguide",
    notfound: {
      title: "Are you lost?",
      text: "Sorry, we couldn't find this page. You'll find more movies and series to explore on the homepage.",
    },
    quiz: {
      titre: "Custom Quiz",
      bienvenue: "Welcome to the Custom Quiz",
      objectif: "Objective",
      objectifTexte: "answer the questions related to your preferences.",
      vitesse: "Attention: speed of answers counts!",
      etape1: "Step 1:",
      etape2: "Step 2:",
      questionXsurY: "Question {{x}} / {{y}}",
      q1: "In which movie does a park full of dinosaurs get out of control?",
      q1rep1: "Godzilla",
      q1rep2: "Jurassic Park",
      q1rep3: "Super Mario Bros. the movie",
      q1rep4: "Ice Age 3",
      repondre: "Please answer below:",
      suivant: "Go to the next question",
      voirReponses: "See my answers to the customization questions",
      modifier: "Edit my answers",
      demarrer: "Start my custom quiz",
      repondreIntro: "Answer these questions to customize the quiz:",
      maReponse: "My answer",
      resultat: "Quiz Result",
      question: "Question {{num}}:",
    },
    home: {
      titre: "CINEGUIDE: All your favorite movies and series in one place",
      slogan: "Browse, search and watch TV and movies from over 300 services.",
      etBienDautres: "and many more",
      top10: "Top 10 this week >",
      meilleuresSeriesAction: "Best Action Series >",
      parceQueVousAimez: 'Because you like "Peaky Blinders"',
      onRegardeQuoi: "What are we watching tonight?",
      erreurGenre: "Please select a genre",
      genre: "GENRE:",
      selectionnezGenre: "Select a genre",
      erreurType: "Please select at least one type",
      type: "TYPE:",
      film: "Movie",
      serie: "Series",
      note: "RATING:",
      selectionnezNote: "Select a rating",
      noteChefOeuvre: "9 to 10 - Masterpiece",
      noteTresBon: "7 to 9 - Very good",
      noteMoyen: "4 to 7 - Average",
      noteMauvais: "0 to 4 - Bad",
      trouverUnFilm: "FIND A MOVIE",
      aucunResultat: "No ",
      filmOuSerie: "movie or series",
      neCorrespond: "matches your criteria 😕",
      essayezFiltres: "Try changing your filters to get more results",
      pasInspiration: "No inspiration for tonight? 🎬",
      utilisezFiltres:
        'Use the filters and click "FIND A MOVIE" to get a personalized suggestion!',
      aVoir: "To watch",
      dejaVu: "Already seen",
      pasEncoreVu: "Not yet seen",
      regarder: "Watch",
      dejaAjoute: "Already added",
      noFilmAvailable: "No movie is available based on your search",
    },
    header: {
      accueil: "Home",
      films: "Movies",
      series: "Series",
      actualites: "News",
      jeux: "Games",
      plus: "More",
      connexion: "Login",
      inscription: "Sign up",
      monCompte: "My account",
      deconnexion: "Logout",
      rechercherPlaceholder: "Search for a movie, series, actor ...",
    },
    footer: {
      accueil: "Home",
      films: "Movies",
      series: "Series",
      actualites: "News",
      plus: "More",
      mentionsLegales: "Legal Notice",
      cgu: "Terms of Use",
      cgv: "Terms of Sale",
      faq: "FAQ",
    },
    cgu: {
      titre: "Terms of Use",
      contenu: "Here are the terms of use for Cineguide.",
    },
    cgv: {
      titre: "Terms of Sale",
      contenu: "Here are the terms of sale for Cineguide.",
    },
    mentionsLegales: {
      titre: "Legal Notice",
      contenu: "Here is the legal notice for Cineguide.",
    },
    faq: {
      titre: "FAQ",
      contenu: "Here is the Cineguide FAQ.",
    },
    profil: {
      titre: "My Profile",
      contenu: "Welcome to your Cineguide profile.",
    },
    film: {
      titre: "Movies",
      contenu: "Browse all movies available on Cineguide.",
    },
    series: {
      titre: "Series",
      contenu: "Browse all series available on Cineguide.",
      noSerieAvailable: "No series is available based on your search",
    },
    jeux: {
      titre: "Games",
      contenu: "Have fun with Cineguide games.",
    },
  },
};
