export default {
  translation: {
    accueil: "Inicio",
    films: "Películas",
    series: "Series",
    actualites: "Noticias",
    connexion: "Conexión",
    inscription: "Registrarse",
    bienvenue: "Bienvenido a Cineguide",
    notfound: {
      title: "¿Te has perdido?",
      text: "Lo sentimos, no hemos encontrado esta página. Puedes encontrar más películas y series para explorar en la página de inicio.",
    },
    quiz: {
      titre: "Quiz Personalizado",
      bienvenue: "Bienvenido al Quiz Personalizado",
      objectif: "Objetivo",
      objectifTexte:
        "responde a las preguntas relacionadas con tus preferencias.",
      vitesse: "¡Atención: la velocidad de las respuestas cuenta!",
      etape1: "Paso 1:",
      etape2: "Paso 2:",
      questionXsurY: "Pregunta {{x}} / {{y}}",
      q1: "¿En qué película un parque lleno de dinosaurios se sale de control?",
      q1rep1: "Godzilla",
      q1rep2: "Jurassic Park",
      q1rep3: "Super Mario Bros. la película",
      q1rep4: "La Era de Hielo 3",
      repondre: "Responde a continuación:",
      suivant: "Pasar a la siguiente pregunta",
      voirReponses: "Ver mis respuestas a las preguntas de personalización",
      modifier: "Modificar mis respuestas",
      demarrer: "Comenzar mi quiz personalizado",
      repondreIntro: "Responde a estas preguntas para personalizar el quiz:",
      maReponse: "Mi respuesta",
      resultat: "Resultado del Quiz",
      question: "Pregunta {{num}}:",
    },
    home: {
      titre:
        "CINEGUIDE: Todas tus películas y series favoritas en un solo lugar",
      slogan:
        "Busca, explora y mira televisión y películas de más de 300 servicios.",
      etBienDautres: "y muchos más",
      top10: "Top 10 esta semana >",
      meilleuresSeriesAction: "Mejores series de acción >",
      parceQueVousAimez: 'Porque te gusta "Peaky Blinders"',
      onRegardeQuoi: "¿Qué vemos esta noche?",
      erreurGenre: "Por favor selecciona un género",
      genre: "GÉNERO:",
      selectionnezGenre: "Selecciona un género",
      erreurType: "Por favor selecciona al menos un tipo",
      type: "TIPO:",
      film: "Película",
      serie: "Serie",
      note: "NOTA:",
      selectionnezNote: "Selecciona una nota",
      noteChefOeuvre: "9 a 10 - Obra maestra",
      noteTresBon: "7 a 9 - Muy buena",
      noteMoyen: "4 a 7 - Regular",
      noteMauvais: "0 a 4 - Mala",
      trouverUnFilm: "ENCONTRAR UNA PELÍCULA",
      aucunResultat: "Ningún ",
      filmOuSerie: "película o serie",
      neCorrespond: "corresponde a tus criterios 😕",
      essayezFiltres: "Intenta cambiar los filtros para obtener más resultados",
      pasInspiration: "¿Sin inspiración para esta noche? 🎬",
      utilisezFiltres:
        '¡Usa los filtros y haz clic en "ENCONTRAR UNA PELÍCULA" para obtener una sugerencia personalizada!',
      aVoir: "Por ver",
      dejaVu: "Ya vista",
      pasEncoreVu: "Aún no vista",
      regarder: "Ver",
      dejaAjoute: "Ya añadido",
      noFilmAvailable: "Ninguna película está disponible según tu búsqueda",
    },
    actualites: {
      chargement: "Cargando artículos...",
      titre: "NOTICIAS",
      page: "Página",
    },
    header: {
      accueil: "Inicio",
      films: "Películas",
      series: "Series",
      actualites: "Noticias",
      jeux: "Juegos",
      plus: "Más",
      connexion: "Conexión",
      inscription: "Registrarse",
      monCompte: "Mi cuenta",
      deconnexion: "Cerrar sesión",
      rechercherPlaceholder: "Buscar una película, serie, actor ...",
    },
    footer: {
      accueil: "Inicio",
      films: "Películas",
      series: "Series",
      actualites: "Noticias",
      plus: "Más",
      mentionsLegales: "Aviso Legal",
      cgu: "Términos de Uso",
      cgv: "Términos de Venta",
      faq: "FAQ",
    },
    cgu: {
      titre: "Términos de Uso",
      contenu: "Aquí están los términos de uso de Cineguide.",
    },
    cgv: {
      titre: "Términos de Venta",
      contenu: "Aquí están los términos de venta de Cineguide.",
    },
    mentionsLegales: {
      titre: "Aviso Legal",
      contenu: "Aquí está el aviso legal de Cineguide.",
    },
    faq: {
      titre: "FAQ",
      contenu: "Aquí está la sección de preguntas frecuentes de Cineguide.",
    },
    profil: {
      titre: "Mi Perfil",
      contenu: "Bienvenido a tu perfil de Cineguide.",
    },
    film: {
      titre: "Películas",
      contenu: "Explora todas las películas disponibles en Cineguide.",
    },
    series: {
      titre: "Series",
      contenu: "Explora todas las series disponibles en Cineguide.",
      noSerieAvailable: "Ninguna serie está disponible según tu búsqueda",
    },
    jeux: {
      titre: "Juegos",
      contenu: "Diviértete con los juegos de Cineguide.",
    },
  },
};
