export default {
  translation: {
    accueil: "Accueil",
    films: "Films",
    series: "Séries",
    actualites: "Actualités",
    connexion: "Connexion",
    inscription: "Inscription",
    bienvenue: "Bienvenue sur Cineguide",
    notfound: {
      title: "Vous vous êtes égaré ?",
      text: "Désolé, nous n'avons pas trouvé cette page. Vous trouverez d'autres films et séries à explorer sur la page d'accueil.",
    },
    quiz: {
      titre: "Quiz Personnalisé",
      bienvenue: "Bienvenue dans le Quiz Personnalisé",
      objectif: "Objectif",
      objectifTexte:
        "répondre aux questions posées en rapport avec vos préférences.",
      vitesse: "Attention : la vitesse des réponses compte !",
      etape1: "Etape 1 :",
      etape2: "Etape 2 :",
      questionXsurY: "Question {{x}} / {{y}}",
      q1: "Dans quel film un parc rempli de dinosaures devient incontrôlable ?",
      q1rep1: "Godzilla",
      q1rep2: "Jurassic Park",
      q1rep3: "Super Mario Bros. le film",
      q1rep4: "L'Âge de Glace 3",
      repondre: "Veuillez répondre ci-dessous :",
      suivant: "Passer à la question suivante",
      voirReponses: "Voir mes réponses aux questions de personnalisation",
      modifier: "Modifier mes réponses",
      demarrer: "Démarrer mon quiz personnalisé",
      repondreIntro: "Répond à ces questions pour personnaliser le quiz :",
      maReponse: "Ma réponse",
      resultat: "Résultat du Quiz",
      question: "Question {{num}} :",
    },
    home: {
      titre: "CINÉGUIDE : Tous vos films et séries préférées au même endroit",
      slogan:
        "Parcourez, recherchez et regardez la télévision et les films de plus de 300 services.",
      etBienDautres: "et bien d'autres",
      top10: "Top 10 cette semaine >",
      meilleuresSeriesAction: "Meilleures séries Action >",
      parceQueVousAimez: 'Parce que vous aimez "Peaky Blinders"',
      onRegardeQuoi: "On regarde quoi ce soir ?",
      erreurGenre: "Veuillez sélectionner un genre",
      genre: "GENRE :",
      selectionnezGenre: "Sélectionnez un genre",
      erreurType: "Veuillez sélectionner au moins un type",
      type: "TYPE :",
      film: "Film",
      serie: "Série",
      note: "NOTE :",
      selectionnezNote: "Sélectionnez une note",
      noteChefOeuvre: "9 à 10 - Chef d'œuvre",
      noteTresBon: "7 à 9 - Très bon",
      noteMoyen: "4 à 7 - Moyen",
      noteMauvais: "0 à 4 - Mauvais",
      trouverUnFilm: "TROUVER UN FILM",
      aucunResultat: "Aucun ",
      filmOuSerie: "film ou série",
      neCorrespond: "ne correspond à vos critères 😕",
      essayezFiltres:
        "Essayez de modifier vos filtres pour obtenir plus de résultats",
      pasInspiration: "Pas d'inspiration pour ce soir ? 🎬",
      utilisezFiltres:
        'Utilisez les filtres et cliquez sur "TROUVER UN FILM" pour obtenir une suggestion personnalisée !',
      aVoir: "À voir",
      dejaVu: "Déjà vu",
      pasEncoreVu: "Pas encore vu",
      regarder: "Regarder",
      dejaAjoute: "Déjà ajouté",
      noFilmAvailable: "Aucun film n'est disponible d'après vos recherches",
    },
    series: {
      noSerieAvailable: "Aucune série n'est disponible d'après vos recherches",
    },
    header: {
      accueil: "Accueil",
      films: "Films",
      series: "Séries",
      actualites: "Actualités",
      jeux: "Jeux",
      plus: "Plus",
      connexion: "Connexion",
      inscription: "S'inscrire",
      monCompte: "Mon compte",
      deconnexion: "Déconnexion",
      rechercherPlaceholder: "Rechercher un film, une série, un acteur ...",
    },
    footer: {
      accueil: "Accueil",
      films: "Films",
      series: "Séries",
      actualites: "Actualités",
      plus: "Plus",
      mentionsLegales: "Mentions Légales",
      cgu: "CGU",
      cgv: "CGV",
      faq: "FAQ",
    },
    cgu: {
      titre: "Conditions Générales d'Utilisation",
      contenu: "Voici les conditions générales d'utilisation de Cineguide.",
    },
    cgv: {
      titre: "Conditions Générales de Vente",
      contenu: "Voici les conditions générales de vente de Cineguide.",
    },
    mentionsLegales: {
      titre: "Mentions Légales",
      contenu: "Voici les mentions légales de Cineguide.",
    },
    faq: {
      titre: "FAQ",
      contenu: "Voici la foire aux questions de Cineguide.",
    },
  },
};
